### ISSUE TITLE
Setting LED current

### ISSUE THREAD

**Issue by DaveLangstaff** [adafruit/Adafruit_CircuitPython_AS7341#1]
Setting the LED current to 0, with sensor.led_current=0 gives the unexpected result of actually setting the current to the maximum value possible, due to wrap around in the calculation.

Suggest modifying line 620 of file to:

        new_current = max(0, min(127,int((led_curent - 4) / 1)))

 to coerce current being set to valid range.

regards
dave Langstaff

**Comment by ladyada** [comment]
! could you submit a PR please? :)

**Comment by DaveLangstaff** [comment]
Hi,

Sorry, I’m new to this – submit a PR?

Regards

Dave Langstaff

**Comment by ladyada** [comment]
yep contribute your fix!
https://learn.adafruit.com/an-introduction-to-collaborating-with-version-control
https://learn.adafruit.com/contribute-to-arduino-with-git-and-github

**Comment by DaveLangstaff** [comment]
Many thanks, I’ll work through the guide and send in the fix

Regards

Dave Langstaff

**Comment by siddacious** [comment]
hi @DaveLangstaff let me know if you've got any questions about the process

**Comment by DaveLangstaff** [comment]
Hi,
Sorry it's taking a while, emf of term business compounded by my Pi deciding to scribble on its sd card.
Should be OK and good to go in a day

Dave

On 14 Dec 2020 6:22 p.m., siddacious <notifications@github.com> wrote:
[RHYBUDD! E-BOST ALLANOL / CAUTION! EXTERNAL E-MAIL]


hi @DaveLangstaff<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDaveLangstaff&data=04%7C01%7C%7C280b426ad19d43f995e008d8a05d447d%7Cd47b090e3f5a4ca084d09f89d269f175%7C0%7C0%7C637435669754921327%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=GrpZwgpdEjg6wtzUXek8odhxIQrcFYHLoX5aICtGsCU%3D&reserved=0> let me know if you've got any questions about the process

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fadafruit%2FAdafruit_CircuitPython_AS7341%2Fissues%2F1%23issuecomment-744623033&data=04%7C01%7C%7C280b426ad19d43f995e008d8a05d447d%7Cd47b090e3f5a4ca084d09f89d269f175%7C0%7C0%7C637435669754931319%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=WvjoSs9mIVqDuVcllPnajYJT5gSPZMfYLzNCrAehxjI%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACTK76TVYGPYLCDXR4DNMOLSUZJXVANCNFSM4UQJJAQQ&data=04%7C01%7C%7C280b426ad19d43f995e008d8a05d447d%7Cd47b090e3f5a4ca084d09f89d269f175%7C0%7C0%7C637435669754931319%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=B9CKllg3gJKCYoRZhS1TBy4dmXp1CzGCbyW27K%2FFX6k%3D&reserved=0>.


----------------------------------------------------------------------------------------------------------------------
Prifysgol y Flwyddyn ar gyfer Ansawdd y Dysgu a Phrofiad Myfyrwr
University of the year for Teaching Quality and Student Experience
(The Times and Sunday Times, Good University Guide 2021)
Rydym yn croesawu gohebiaeth yn Gymraeg a Saesneg. Cewch ateb Cymraeg i bob gohebiaeth Gymraeg ac ateb Saesneg i bob gohebiaeth Saesneg. Ni fydd gohebu yn Gymraeg yn arwain at oedi.
We welcome correspondence in Welsh and English. Correspondence received in Welsh will be answered in Welsh and correspondence in English will be answered in English. Corresponding in Welsh will not involve any delay.

**Comment by siddacious** [comment]
@DaveLangstaff No worries, take your time! We'll be here when you're ready.

Enjoy the holidays :)

**Comment by DaveLangstaff** [comment]
Hi,

Happy New Year.

I'm picking things up after the break and was wondering your opinion on the maximum current for the LED and how to approach this.

The AS7341 itself allows for an LED current of up to 258mA, so theoretically, the code could use this as a maximum value. However the LED used on the Adafruit breakout board (EAHC2835WD6) has a stated maximum of 180mA, so the library probably shouldn't go above that.

Over the break I hooked up a breakout board in a sealed box and recorded the sensor values for different currents up to 150mA (see attached PNG). As you can see from the plot, the LED output seems pretty linear up to 100mA but above this, there seems to be some current limitation. I've checked this with code running on both an Pi and also an Arduino, and got the same result, so it does seem a feature of the breakout board  - probably due to the 7312 voltage convertor IC used.

I'd be interested to hear your feelings on this and how this should be reflected in the library

Regards

Dave Langstaff

**Comment by caternuson** [comment]
Closing. Fixed with #9.
