### ISSUE TITLE
AS7341.reset() does nothing

### ISSUE THREAD

**Issue by house-rat** [adafruit/Adafruit_CircuitPython_AS7341#12]
The docstring says: `"""Resets the internal registers and restores the default settings"""`, but the function is empty.

Apologies if this is on the todo list already.

I tried toggling `self._power_enabled`  as a quick workaround, but previous values persisted.

**Comment by ladyada** [comment]
yeah we should probably just remove it. wanna send in a PR?

**Comment by jposada202020** [comment]
Solve by #14 . Thanks. closing this.
