### ISSUE TITLE
clear channel

### ISSUE THREAD

**Issue by marcelokauffman** [adafruit/Adafruit_CircuitPython_AS7341#16]
How can I get the clear channel reading?

**Comment by jposada202020** [comment]
Hello @marcelokauffman is this an issue with the library?
If is general support regarding the product that you bought you could ask for support in the Adafruit Forums.
For general questions and support you could ask in the Adafruit Discord Channel.
Thanks.

**Comment by bjones14** [comment]
> How can I get the clear channel reading?

https://github.com/adafruit/Adafruit_CircuitPython_AS7341/pull/19 - pull request in works to add access for Clear and NIR channels
