### ISSUE TITLE
Clear and NIR Accessors

### ISSUE THREAD

**Issue by rickyroze** [adafruit/Adafruit_CircuitPython_AS7341#18]
Is there a way to get a reading from the Clear and NIR channels on the AS7341?  On line 379 of 'adafruit_as7341.py' it is still listed as a TODO.  Is this still something that is planning on being added?  Thanks so much!

**Comment by bjones14** [comment]
@rickyroze I just submitted a pull request for this reason, hope to see it added to be available to everyone else soon!

https://github.com/adafruit/Adafruit_CircuitPython_AS7341/pull/19

**Comment by jepler** [comment]
Closing as the related PR was merged!
