### ISSUE TITLE
Is it possible to adjust the integration time step and number of steps?

### ISSUE THREAD

**Issue by sgbaird** [adafruit/Adafruit_CircuitPython_AS7341#30]
https://github.com/sparks-baird/self-driving-lab-demo/issues/17

i.e. [`astep`](https://docs.circuitpython.org/projects/as7341/en/latest/api.html#adafruit_as7341.AS7341.astep) and [`atime`](https://docs.circuitpython.org/projects/as7341/en/latest/api.html#adafruit_as7341.AS7341.atime)

Is this as simple as:
```python
i2c = board.I2C()
sensor = AS7341(i2c)
sensor.astep = 10
sensor.atime = 100
```
(similar to the [flicker detection example](https://docs.circuitpython.org/projects/as7341/en/latest/examples.html#flicker-detection), modifying the property after class instantiation)

Also, what are the default values for these?

**Comment by caternuson** [comment]
Yes. Use the `astep` and `atime` properties to change the values.

The defaults are `atime=100` and `astep=999`.

**Comment by sgbaird** [comment]
@caternuson do you know what the default gain is (e.g. 64x)? I was looking through the code and having trouble finding it. I'm using a separate library for MicroPython (due to lack of Blinka/CircuitPython support for Pico W), and I think the defaults are different.

**Comment by caternuson** [comment]
128x
https://github.com/adafruit/Adafruit_CircuitPython_AS7341/blob/f16d14a4f16c0b997d241759a6a728e6048e0383/adafruit_as7341.py#L368-L370

**Comment by sgbaird** [comment]
🤦 thank you!
