### ISSUE TITLE
Is there a defined "band" for each channel?

### ISSUE THREAD

**Issue by sgbaird** [adafruit/Adafruit_CircuitPython_AS7341#31]
![image](https://user-images.githubusercontent.com/45469701/187047853-d51f3daa-59dd-4750-869d-36c3ae73c90e.png)

I assumed 415 meant the measurement was centered at 415nm, though I'm wondering now based on the description of "415nm band" etc. Do you mind clarifying? Where it's centered? What kind of width it has?

**Comment by FoamyGuy** [comment]
I don't really have any prior experience or understanding of this type of sensor or it's readings, so possibly someone who does will have better ideas. 

I did find this section of in the data sheet that seems to be relevant to the information you're after:
![image](https://user-images.githubusercontent.com/2406189/187228162-bc40baa7-3a9a-44b2-8feb-8a2fa00fe54c.png)

The [datasheet](https://ams.com/documents/20143/36005/AS7341_DS000504_3-00.pdf/) is linked on the downloads page in the product learn guide: https://learn.adafruit.com/adafruit-as7341-10-channel-light-color-sensor-breakout/downloads. Maybe it contains the information you're interested in, even if not from this table specifically. I would assume the datasheet (and perhaps arduino driver if there is one) was likely the primary reference(s) used when writing this driver.

**Comment by caternuson** [comment]
Also see Fig. 18 and 19 in the datasheet. The wave lengths are essentially the peaks of the curves for each band. This may or may not be the true center of the band depending on how symmetric the curve is around the peak.

Closing since this is not an issue with library code. Answers are in datasheet. More detailed info would require contacting the sensor manufacturer.

**Comment by sgbaird** [comment]
@FoamyGuy and @caternuson thank you! This is perfect. Somehow didn't cross my mind to check the datasheet. Much appreciated!
