### ISSUE TITLE
Wrong Default for Gain

### ISSUE THREAD

**Issue by NeoStormer** [adafruit/Adafruit_CircuitPython_AS7341#40]
According to the datasheet the default should be 9 or 256x:

![image](https://github.com/adafruit/Adafruit_CircuitPython_AS7341/assets/3752290/97a145df-27a0-440b-8e41-14e4d12676b4)

I could see this being an issue for someone coming from Arduino or looking at the datasheet graphs.

**Comment by FoamyGuy** [comment]
@NeoStormer do you happen to have a link for data sheet or a reference of what page or section this quote was pulled from?

Are you interested in submitting a PR with this change?

**Comment by FoamyGuy** [comment]
I've had a closer look into the datasheet and I'm not sure the sections referencing that default value are for features that this library implements. The references I could find are:
![image](https://github.com/user-attachments/assets/20a46cbe-5fa6-4e73-8bf0-4a715370def2)

Which note the default values for `AGC_FD_GAIN_MAX` and `AGC_AGAIN_MAX` which are in the register `0xCF`

The gain value that is implemented in this library currently is rooted here: https://github.com/adafruit/Adafruit_CircuitPython_AS7341/blob/0a7b934ce8a0c0bcdda18abc5d376aa37ae9301b/adafruit_as7341.py#L344 and it's set to us the register `_AS7341_CFG1` or `0xAA` which is documented in a different section of the datasheet.

![image](https://github.com/user-attachments/assets/b4673dc0-9b3a-44d6-95a0-347ec2e71f38)

In that section it doesn't mention anything about a default value. 

As far as I can tell nothing in this library interacts with register 0xCF at all currently.  So my understanding is that the defaults mentioned for values in that register don't apply to this driver as it's written today.

I'm going to close this for now. Feel free to re-open if you believe there is still some issue and can provide more details.
