### ISSUE TITLE
Getting error at line 195 during import - object 'str" is not a tuple or a list

### ISSUE THREAD

**Issue by monroepattillo** [adafruit/Adafruit_CircuitPython_AS7341#8]
https://github.com/adafruit/Adafruit_CircuitPython_AS7341/blob/e73cea4d39ccdfbabfd208cedfbe0c6f092b78e1/adafruit_as7341.py#L195

Maybe instead formalize second parameter on request to namedtuple as a square bracketed list of string items or as a string containing items delimited by comma space?  Maybe CircuitPython can't handle the necessary string to list conversion.

Am attempting to implement software based spectroscope for educational demonstrations using Adafruit # 3500 Trinket M0 connected to Adafruit # 4698 AS7341 breakout.

First time submitting regarding Adafruit offerings.  Please let me know if my style and content are conformant to expectations.

**Comment by ladyada** [comment]
is the example not working?

**Comment by caternuson** [comment]
hmmm. trinket m0 thing?
```python
Adafruit CircuitPython 6.1.0 on 2021-01-21; Adafruit Trinket M0 with samd21e18
>>> from collections import namedtuple
>>> _SmuxOut = namedtuple("_SmuxOut", "DISABLED ADC0 ADC1 ADC2 ADC3 ADC4 ADC5")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: object 'str' is not a tuple or list
>>> 
```

```python
Adafruit CircuitPython 6.1.0 on 2021-01-21; Adafruit ItsyBitsy M4 Express with samd51g19
>>> from collections import namedtuple
>>> _SmuxOut = namedtuple("_SmuxOut", "DISABLED ADC0 ADC1 ADC2 ADC3 ADC4 ADC5")
>>>  
```

**Comment by caternuson** [comment]
I patched this real quick to test, but ran into new issue:
```python
Adafruit CircuitPython 6.1.0 on 2021-01-21; Adafruit Trinket M0 with samd21e18
>>> import as7341_simpletest
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "as7341_simpletest.py", line 6, in <module>
  File "adafruit_as7341.py", line 199, in <module>
  File "adafruit_as7341.py", line 229, in AS7341
MemoryError: memory allocation failed, allocating 184 byte
>>> 
```
This library's use of register may make it not work for small boards like Trinket M0.

**Comment by monroepattillo** [comment]
Haven’t tried the example in CircuitPython on my full Pi, but given the nature of the source code change I would assume example works on full Python.  Change is just to help CircuitPython on small breakouts.  No need to make CircuitPython any larger for increased compatibility with larger systems.  With suggested change it now imports successfully on Trinket M0 target (using mpy-cross to make it fit).  It’s just for a spectrographic educational demonstrator for a public astronomical observatory so reproducibility on a shoestring budget is a factor as is demonstration of mu/CircuitPython ease of use.  

 

AS7341 was demonstrated on an Itsy Bitsy M0, same processor speed, same RAM, same FLASH, just 2MB of serial FLASH and likely done in Arduino not CircuitPython.  But it’s just a simple educational demonstrator, not overly concerned about samples per second, recording trends, or sophistication of report output.  Besides, the suggested change would be expected to work on breakouts with greater resources and full PIs with no board specific change.

 

Thanks,

 

Monroe

**Comment by monroepattillo** [comment]
It was demonstrated on an Itsy Bitsy M0 express (likely using Arduino, not CircuitPython).  Just looking to do a simple spectrographic educational demonstrator for a public astronomical observatory.  Suggested source code change is just a helper for CircuitPython and should import successfully on larger platforms.

 

Monroe

**Comment by caternuson** [comment]
OK. Sounds like we could close this then? Seems like boards big enough to use this library can also parse that string syntax.

**Comment by ladyada** [comment]
it would work great with our arduino library, please try that!

**Comment by monroepattillo** [comment]
Please close it.  

 

Given that I’m developing the demonstration program and I have access to the library source I’ll try a different software design approach for the AS7341 interface which might allow it to work on the Trinket M0 using CircuitPython which was a goal of the activity.  Maybe dissolving the library into the program.  Not the way for your business to do it.  Not good for modularity and reusability, but it might allow progress.  Effort and time will tell whether or not I’m successful.  While it’s more likely to make it fit using Arduino that elevates the required knowledge baseline and I’d really rather they focus on the spectroscopy aspects.  And while it is likely to run it on a bigger board that raises the total cost of ownership baseline which means it is less likely they will reproduce the educational demonstration at other sites.  

 

I came up during the era of the KIM-1 and assembly language.  My software developer capabilities includes a resources shoehorn, assuming one has the time, patience, and skills, and the project scope and schedule permits it.  Plus I’m retired and I’ve cut back to working only three projects at a time.  It sounds like fun to me.

 

Thank you for your efforts,

 

Monroe

**Comment by monroepattillo** [comment]
Understood.  Consider the issue closed.  I have the skills to Arduino it if required.  For now I have the library source and am going to play a little longer in CircuitPython which is great stuff.  For this demo maybe redesign and dissolve the interface library into the program to reduce the Python full feature set and memory requirements.  Processor is sufficiently fast.  Samples per second is not an issue.  If I need code storage space there are always the Express variants.  I’m stubborn, but only to a point, or so my owning a Pi 4 with 4GB RAM (but drooling over the 8GB model) and 32GB microSD (but wanting an NVMe interface) would seem to indicate, but that Pi 4 is for the dirt cheap radio astronomy interferometry project.  

 

Having smaller boards that support CircuitPython make the local FLASH look like storage to the host computer on the other side of the USB connection is a great concept and is very well integrated.  Have you ever considered turning it the other way around and allowing the small board to make use of the considerably larger storage of the host computer across the USB connection for program and data storage?  Then you wouldn’t need to add the SPI FLASH chip and you wouldn’t be limited to 2MB to keep costs and board footprint contained.  If individual small boards had a world unique identifier then software on the host computer could set up both board instance agnostic and per board instance specific storage profiles.  The limit would be the number of full speed USB 2.0 ports supported by the host computer using hubs.  A reusable multiple sensor network could be created with each sensor having its own dedicated small board.  The next gen beyond M0 is likely to have a faster processor, maybe twice the RAM, likely with USB 3.0 with a type-C connection, but will still likely be limited on FLASH storage.  This approach would remove that constraint.  Just a thought.

 

Adafruit is great, thank you,

 

Monroe

**Comment by ladyada** [comment]
ok closing. i think a bigger/more capable board would work with circuitpython. like a STM32, nRF, ESP32S2 or M4 - even the new pico would be good! m0 is very very minimal :)

**Comment by ladyada** [comment]
@caternuson or @dherrada  can ya add a note to the readme that m0 wont work?

**Comment by monroepattillo** [comment]
Made source changes to shrink my app and AS7341 driver to fit FLASH, but RAM is just too tight due to register allocations.  Have already ordered an ItsyBitsy M4 Express, hopefully the sure cure for both FLASH and RAM while keeping with the CircuitPython coding simplicity and the physical size and total cost of ownership still less than a full Pi.

 

I picked up on the M4 by a side comment heard during a video, went to look it up at Mirochip, saw its level of resources, then back to Adafruit, found the ItsyBitsy M4 Express, price bump was tolerable to the project, and ordered it.

 

Maybe the site could use a cross product table showing comparative levels of resources and basic performance.

 

Regards,

 

Monroe Pattillo
